name = "Tagalog"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.tl"

[windows]
system_product_code = "375D1CE1-6A89-43F1-A429-368860DD19C2"
msoffice_product_code = "EFCFBA6F-C92C-4A69-9F89-DBCDECD45CB0"
