spellername = "Tagalog"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Tagalog spellchecker"
tl = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Tagalog, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
tl = "TRANSLATE: A spellchecker for Tagalog, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.tl"

[windows]
system_product_code = "{5C0A4842-E902-4586-B8D5-771513E060E3}_is1"
legacy_product_codes = [
    { value = "375D1CE1-6A89-43F1-A429-368860DD19C2", kind = "nsis" },
    { value = "EFCFBA6F-C92C-4A69-9F89-DBCDECD45CB0", kind = "nsis" }
]
