template = "https://github.com/giellalt/template-lang-und"
rev_id = 340
template_sha = "1186578fa79468b8b3349a52ce4880edc3ce8803"

[replacements]
__GLOTTOLOG_ID__ = "taga1270"
__REPO__ = "lang-tgl"
__UND2C__ = "tl"
__UNDEFINED__ = "Tagalog"
__UND__ = "tgl"
