template = "https://github.com/giellalt/template-lang-und"
rev_id = 335
template_sha = "656172fb5ca68a68ee8547c7bc0cd1ce3f605fd7"

[replacements]
__GLOTTOLOG_ID__ = "taga1270"
__REPO__ = "lang-tgl"
__UND2C__ = "tl"
__UNDEFINED__ = "Tagalog"
__UND__ = "tgl"
