template = "https://github.com/giellalt/template-lang-und"
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "taga1270"
__REPO__ = "lang-tgl"
__UND2C__ = "tl"
__UNDEFINED__ = "Tagalog"
__UND__ = "tgl"
