[package]
name = "tgl"
human_name = "Tagalog"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.tgl]
filename = "tl-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-tgl"
platform = "windows"
uuid = "375D1CE1-6A89-43F1-A429-368860DD19C2"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.tl"
package = "speller-tgl"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-tgl-mso"
platform = "windows"
uuid = "EFCFBA6F-C92C-4A69-9F89-DBCDECD45CB0"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-tgl"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
